[project]
name = "programming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eyad Jawad", email = "ayadmansr@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.10.3",
    "python-ripgrep>=0.0.9",
    "ripgrep>=15.1.0",
    "ripgrep-rs>=0.4.2",
]

[project.scripts]
programming = "programming:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
