[project]
name = "programming"
version = "0.1.0"
description = "A script that turns obsidian markdown files into html and puts them a website."
readme = "README.md"
authors = [
    { name = "Eyad Jawad" }
]
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.10.3",
    "rapidfuzz>=3.14.6",
    "ripgrep-rs>=0.4.2",
]

[project.scripts]
programming = "programming:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.1",
    "ruff>=0.16.6",
]
